# Task 1

In [80]:
import numpy as np
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Task 2

In [3]:
np.ones((3, 3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# Task 3

In [5]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a[a % 2 == 1]

array([1, 3, 5, 7, 9])

# Task 4

In [73]:
a = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])  
odd_values = (a%2 == 1) 
a[odd_values] = -1
a

array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10])

# Task 5

In [74]:
row = np.array([1,2,3,4,5,6])
matrix = row.reshape(2, 3)
matrix

array([[1, 2, 3],
       [4, 5, 6]])

# Task 6

In [76]:
a = np.arange (1,17).reshape (4,4)  
b = np.arange (17,33).reshape (4,4) 
c = np.dot(a,b)
sum =np.sum(c)
print(c)
print(sum)

[[ 250  260  270  280]
 [ 618  644  670  696]
 [ 986 1028 1070 1112]
 [1354 1412 1470 1528]]
13648


# Extension

# Task 1

In [79]:
# First Method
row_1 = np.array([1,1,1,2,2,2,3,3,3,1,2,3,1,2,3,1,2,3])
row_1

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [69]:
# Second method
an_array = np.array([1,2,3])
repeats_array_1 = np.transpose([an_array] * 3)
repeats_array_2 = np.tile(an_array, (3, 1))
repeats_array = np.concatenate((repeats_array_1, repeats_array_2))
result = repeats_array.flatten()
result

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

# Task 2

In [49]:
a = np.arange(1,6)
b = np.arange(4,10)
for i in a:
    for j in b:
        if i == j:
            index = np.argwhere(b==j)
            b = np.delete(b,index)
print(b)

[6 7 8 9]


# Task 3

In [57]:
b = np.arange(4,10)   # b is defined again because it was changed in the prvious task
arr = np.concatenate((a, b))
sum2 = 0
for i in arr:
    if 3 <= i <= 7:
        sum2 += i
print(sum2)

34
